- name: Install PyMySQL
  pip:
    name: pymysql
    state: present
    
- name: create database
  community.mysql.mysql_db:
    login_host: "terraform-20230414230142894800000010.crdwcrqpgnyb.us-east-1.rds.amazonaws.com"
    login_user: "manny"
    login_password: "devopspbl"
    name: mannydb
    collation: utf8_general_ci
    encoding: utf8
    state: present

- name: Input tooling credentials
  ansible.builtin.replace:
    path: /var/www/html/functions.php
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
  loop:
    - { regexp: '^mysql.tooling.svc.cluster.local', line: "terraform-20230414230142894800000010.crdwcrqpgnyb.us-east-1.rds.amazonaws.com" }
    - { regexp: '^admin', line: "manny" }
    - { regexp: '^tooling', line: "mannydb" }
    - { regexp: '^admin', line: "devopspbl" }


